-- 코드를 작성해주세요
SELECT ID,
    CASE
    WHEN E.RANKING * 100 / TOTAL_COUNT <= 25 THEN 'CRITICAL'
    WHEN E.RANKING * 100 / TOTAL_COUNT <= 50 THEN 'HIGH'
    WHEN E.RANKING * 100 / TOTAL_COUNT <= 75 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT *, 
      RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING,
      COUNT(*) OVER() AS TOTAL_COUNT
      FROM ECOLI_DATA) E
ORDER BY ID;