# -- 코드를 입력하세요
# SELECT *#F.FLAVOR
# FROM  FIRST_HALF F
# JOIN JULY J
# ON F.FLAVOR = J.FLAVOR
# GROUP BY F.FLAVOR
# HAVING SUM(F.TOTAL_ORDER + J.TOTAL_ORDER)
# # ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
# # LIMIT 3;
SELECT A.FLAVOR FROM FIRST_HALF A, JULY B
WHERE A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
HAVING SUM(A.TOTAL_ORDER + B.TOTAL_ORDER)
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC LIMIT 3