-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    (SELECT CODE
    FROM SKILLCODES
    WHERE NAME LIKE '%Python%') +
    (SELECT CODE
    FROM SKILLCODES
    WHERE NAME LIKE '%C#%')    
) != 0
ORDER BY ID;